### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by mystilleef** [google/vpn-libraries#18]
Is a Linux client in the works? It's ironic Linux isn't currently supported. Is it also possible to provide authentication details for OpenVPN clients that already ship with most Linux Desktop environments?

**Comment by anefabo** [comment]
Hi Lateef, thanks for your inquiry. No, we don't have a Linux client currently in the works. We do appreciate your inquiry though and might consider it in the future.

**Comment by mystilleef** [comment]
Why no love for Linux? I imagine this product was built on Linux using open source libraries. Am I missing something?

**Comment by vlgs7** [comment]
I don't think there should be a Linux side, it will undoubtedly be abused

**Comment by MeesJ** [comment]
I second that. The Google One VPN works great, Linux users should be allowed to use it too, without using workarounds. Please add native Linux support to the Google One VPN!

> I don't think there should be a Linux side, it will undoubtedly be abused

I see no reason why the VPN would be abused more on Linux than on other operating systems.

**Comment by vlgs7** [comment]
> If Linux can use it, there will be a large number of proxy servers applying Googleonevpn, which will affect the experience of subscribers. Unfortunately, the official recently give the VPN to 100g subscriptions. This again lowers the barrier to entry.

**Comment by MeesJ** [comment]
First of all, not all Linux users do these malicious things. Second, the Google One VPN should be able to deal with that. For comparison, Cloudflare'
s (free) VPN called [WARP](https://blog.cloudflare.com/announcing-warp-for-linux-and-proxy-mode/) also has Linux support and still works fine.

**Comment by vlgs7** [comment]
Cloudflare` free warp was already abused. I hope Google One Vpn group can handle the problem in the  future. bro, I trust you don`t,but someone else will apply it to their proxy server to earn money.You konw, in some countries, not even Google, YouTube ... can be accessed. They will find any ways to get good experience.

**Comment by ptr1337** [comment]
Little Bump.
Using Google VPN since a bunch of time and really like it on my MacBook and iPhone.

I really would like to see to get also Linux Support, so my Desktop can be also covered from it.
Also Google One would be for a quite big user base on on more system available.
Please consider it to implement.

**Comment by guiodic** [comment]
Dears, please support Linux, thank you!

**Comment by bwiltse** [comment]
+1 for Linux support

**Comment by Nardol** [comment]
Google have never really considered Linux, for example there is no official Google Drive for Linux so I am not surprised it is the same for VPN, no need to speculate about malicious Linux users :wink: there is Chrome but that's all we could expect IMHO.

**Comment by onyxcode** [comment]
unfortunately google will make up excuses because they suck ass. jokes on them because ill just use warp.

**Comment by mystilleef** [comment]
> unfortunately google will make up excuses because they suck ass. jokes on them because ill just use warp.

Warp isn't a VPN though. 

It just baffles me that Google uses Linux for everything and makes money of the community, but refuses to provide first class support for the same community it thrives off. 

This VPN client is written uses FLOSS libraries, yet nobody can tell us why it isn't available for Linux. 

If Mozilla can provide a VPN client for Linux, it's absurd that Google won't. But they claim they love FLOSS though.

**Comment by bermudi** [comment]
+1 for Linux support

**Comment by paolosantarsiero** [comment]
+1 for Linux support

**Comment by ArcCal** [comment]
+1 for Linux support

**Comment by revellion** [comment]
+1 for linux support aswell

**Comment by balister** [comment]
+1 for linux

**Comment by 7HE-W0R1D** [comment]
+1 for linux

**Comment by achandi** [comment]
+1 for linux

**Comment by ckdarby** [comment]
+1 for Linux or just provide CLI instructions for openconnect

**Comment by jh-devv** [comment]
+1 for Linux support

**Comment by mguzmann** [comment]
+1 for Linux support

**Comment by gleisonmalheiros** [comment]
+1 for Linux support

**Comment by codechipped** [comment]
I would also like to see Linux support.

**Comment by AnAlligatorPear** [comment]
+1 for Linux support

**Comment by onyxcode** [comment]
+1 Why has Google ignored this for so long???

**Comment by danawitha** [comment]
1+ for Linux support!

**Comment by Euro-pol** [comment]
+1

**Comment by ShoeUnited** [comment]
for the love of shit cakes cover the fucking os 

all tests geniuses and Linux porting is above your skill level?

it's a vpm ffs

**Comment by kiozen** [comment]
+1

**Comment by ThatBlockyPenguin** [comment]
+1

**Comment by angelimartinez** [comment]
***@***.***

***@***.***

**Comment by BitesizedLion** [comment]
I really see no reason why a single google employee can't take on this task, it's just IPSEC?

**Comment by Theinatorinator** [comment]
Bump!

**Comment by lots0logs** [comment]
As others have stated, we don't need an app. Just give us the connection details we can use with openvpn client. 🙏

**Comment by jh-devv** [comment]
> As others have stated, we don't need an app. Just give us the connection details we can use with openvpn client. 🙏

@lots0logs 
This is so true!!

**Comment by MeesJ** [comment]
> > As others have stated, we don't need an app. Just give us the connection details we can use with openvpn client. 🙏
> 
> Not possible, it does not use OpenVPN, the way they implemented this is not as easy as just giving connection details

A simple CLI tool like Cloudflare WARP has would certainly be appreciated by most people here as well

**Comment by rafaeldrs** [comment]
I just wana say that I agree with most of u. A linux client is needed. I feel like Linux is the most "Google" OS. 
If Linux support is not possible, at least a Chrome extension to connect to the VPN.

**Comment by flatmax** [comment]
+1 for linux support

**Comment by larsaars** [comment]
+1 for linux support

**Comment by Cpyrighted** [comment]
+1 for linux support, linux is the future at this point with great OS'es like Nobara and Pop!_Os, been using Pop!_Os for 7 months now have no intention of ever returning to Windows.

We need major companies to make basic paid features available on all devices, especially linux.

**Comment by xzaz** [comment]
After careful consideration.... 

+1 for linux support.

**Comment by nomadfh** [comment]
You could at the very least allow for openvpn support. We don't even really need a client. I mean jeez maybe a chrome extension? Literally anything?

**Comment by jehov4** [comment]
Might as well:

+1

**Comment by skoogh00** [comment]
+1

**Comment by yunielrc** [comment]
LINUX SUPPORT!!!, I'M PAYING FOR THIS, WHY ARE YOU FORCING ME TO USE WINDOWS

**Comment by mauromarinoni** [comment]
+1

**Comment by hello12324** [comment]
Hello Google VPN Team, 

I use Linux and I'm interested in your VPN. It's a bummer that Google One VPN doesn't support Linux yet. There are lots of us using Linux, especially those who care about security and privacy. We'd really like to use Google One VPN.Expanding to Linux might be tough, but it's worth it. Linux is big in servers, academics, and with devs. By supporting Linux, you'd attract more techy users.We're eager to try Google One VPN on Linux and can help test it. Hope you'll think about this. Looking forward to Linux support in the future.Cheers

Hello12324

**Comment by tbukfrc** [comment]
+1 for Linux support.

**Comment by pohlt** [comment]
+1 for Linux support

**Comment by d-0-c** [comment]
+1

**Comment by lpadgett** [comment]
Please, Linux support!

**Comment by joke2k** [comment]
:+1:

**Comment by davidgross** [comment]
+1 for Linux support!!

**Comment by giulio-quaresima** [comment]
+1 for Linux support!

**Comment by romaluca** [comment]
+1 for Linux support!

**Comment by AlexGerwer** [comment]
I have been trying to make use of VPN by GoogleOne to protect my entire network, per the attached email thread.  I am amazed at how Google will reply with completed irrelevant information and questions.  Getting in touch by phone is virtually impossible.  I have been a Google customer for years.  This is the first time that I have asked for their help.  It has been a futile exercise.  Maybe someone on here can help.  I would love to speak with the product manager for VPN by GoogleOne.

[Gmail - RE_ HP LaserJet Pro 400 Color MFP M475dw Will not Connect on New Orbi RBR875 Network.pdf](https://github.com/google/vpn-libraries/files/13994123/Gmail.-.RE_.HP.LaserJet.Pro.400.Color.MFP.M475dw.Will.not.Connect.on.New.Orbi.RBR875.Network.pdf)
[Gmail - [2-5200000036147] Your Google Support Inquiry_ Case ID.pdf](https://github.com/google/vpn-libraries/files/13994125/Gmail.-.2-5200000036147.Your.Google.Support.Inquiry_.Case.ID.pdf)

**Comment by BitesizedLion** [comment]
> I have been trying to make use of VPN by GoogleOne to protect my entire network, per the attached email thread. I am amazed at how Google will reply with completed irrelevant information and questions. Getting in touch by phone is virtually impossible. I have been a Google customer for years. This is the first time that I have asked for their help. It has been a futile exercise. Maybe someone on here can help. I would love to speak with the product manager for VPN by GoogleOne.
> 
> [Gmail - RE_ HP LaserJet Pro 400 Color MFP M475dw Will not Connect on New Orbi RBR875 Network.pdf](https://github.com/google/vpn-libraries/files/13994123/Gmail.-.RE_.HP.LaserJet.Pro.400.Color.MFP.M475dw.Will.not.Connect.on.New.Orbi.RBR875.Network.pdf) [Gmail - [2-5200000036147] Your Google Support Inquiry_ Case ID.pdf](https://github.com/google/vpn-libraries/files/13994125/Gmail.-.2-5200000036147.Your.Google.Support.Inquiry_.Case.ID.pdf)

This is not the place, nobody here will help you with a support request because we can't do anything, you won't be able to reach any product managers either.

**Comment by jnowe** [comment]
As I'm a **customer who pays** for Google One Vpn, provide me a solution to use my VPN on Linux.

**Comment by AugustH** [comment]
+1 for linux support

**Comment by Chambana** [comment]
+1 on the linux support request

**Comment by edstewbob** [comment]
+1 for linux support

**Comment by BitesizedLion** [comment]
Commenting "+1" contributes nothing other than spam people's notifications & emails who actually want to be updated on this.

Press "thumbs up" on the issue instead.

**Comment by AntoninSlejska** [comment]
There is no Google Drive and no Google VPN for Linux. The Linux desktop market share is 4% now. It is not much, but it is growing (~30% in the last year). See: https://gs.statcounter.com/os-market-share/desktop/worldwide
For me would be Google One subscription quite interesting, but I use Linux.

**Comment by jls42** [comment]
+1 for linux support :)

**Comment by guiodic** [comment]
After more than a year, Google doesn't even respond with a sound bite.

**Comment by ABHax101** [comment]
Still no linux support?

**Comment by RockManJoe64** [comment]
Linux support please! @google-admin

**Comment by zastlx** [comment]
+1 linux support

**Comment by tlefort** [comment]
+1, Linux support please !

**Comment by siwilliam2023** [comment]
Google announced today that the VPN by Google One is shutting down in the coming months.
[Google One VPN will be discontinued, Pixel VPN remains with upgrade coming](https://9to5google.com/2024/04/11/google-one-vpn-discontinued/)

**Comment by nomadfh** [comment]
> Google announced today that the VPN by Google One is shutting down in the coming months.
> 
> [Google One VPN will be discontinued, Pixel VPN remains with upgrade coming](https://9to5google.com/2024/04/11/google-one-vpn-discontinued/)

Google absolutely refuses to support a single thing for more than 5 minutes

**Comment by lowedaniel** [comment]
Thank you for your feedback on the libraries for VPN by Google One. Due to the planned turndown of the VPN, this repo will soon be archived. I’m marking this issue as closed. Thank you again for your input.
