### ISSUE TITLE
Information for Service Providers (Publication of IP Ranges for Identification / Allow Listing)?

### ISSUE THREAD

**Issue by tunaarmadillo** [google/vpn-libraries#19]
Hi - is there any guidance information for service providers to ensure we can optimise for users on the Google One VPN (e.g. identify and not block requests/connections from the VPN!) similar to that provided by Apple for Private Relay:
https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay

**Comment by anefabo** [comment]
Thanks for the question. Yes, we also provide our IP ranges here: 
For VPN by Google One: https://www.gstatic.com/g1vpn/geofeed
For Fi VPN: https://www.gstatic.com/fi/bridge/ipgeofeed.txt

We haven't published specific guidelines for our VPN solution, but you can refer to these guidelines from Android for network operators to improve VPN user experience in general (not just for Google VPNs): https://source.android.com/docs/core/connect/vpn-ux

**Comment by tunaarmadillo** [comment]
Thank you - is there any suggested frequency with which we should check those IP ranges for updates?
Can we rely on the 304 Not Modified status code if just making HEAD requests or should we make a full GET and keep track of the checksum for any changes?

**Comment by smhendrickson** [comment]
Hey Josh, although I believe 304 should work on gstatic.com please use the checksum. It is directly tested by our generation infra. We aim to update the file infrequently and long before we start using IPs published within. I'd recommend daily polling to ensure you have a reasonably fresh copy. We can't make any specific promises on rollout timelines at this time.

Hope this helps. Best,
Scott
