### ISSUE TITLE
One VPN not starting after device reboot

### ISSUE THREAD

**Issue by wanam** [google/vpn-libraries#2]
Having One VPN is working fine on my Pixel 6 / Android 12, but when I reboot the device, the VPN is not automatically connected, and the "Block internet if VPN disconnects" feature is not working as well because I guess the app is not fired correctly on boot.

Other thing, why we cannot set the One VPN to "Always ON":

![Screenshot_20211210-101318](https://user-images.githubusercontent.com/739291/145549326-c0a3c1c3-47a8-42fa-bc0a-f294106a614c.png)

**Comment by wanam** [comment]
An other confusing bug, after unlocking the lockscreen following a device reboot, I get the "VPN by Google One" tile active, even if the vpn service is not connected & running.

I have to click on the tile to start the service correctly.

Checking the logcat I don't see any errors related to the vpn service (using the key words: vpn, ppn, Krypton, Xenon) except the info about ppn tile creation:
`12-10 11:18:04.570  1979  1979 D QSTileHost: Creating tile: custom(com.google.android.apps.subscriptions.red/.ppn.quicksettings.PpnTileService)`

I'm running Android 12 Nov 2021 build.

**Comment by ronaldkozoman** [comment]
Hi, thanks for your interest and comments.  The Feature is working as intended.  In this selection, "Block" is not supported (product decision).  The PPN feature does try to stay on through network events as is possible.  Thank you again for your interest, please reach out if you have questions.  -the Google PPN team
