### ISSUE TITLE
Flutter crash, Router usage, VPN selection - Feedback / Suggestions. 

### ISSUE THREAD

**Issue by joetimmy** [google/vpn-libraries#20]
1) 

Error Code in terminal: Unable to create FlutterView; no MTLDevice or MTLCommandQueue 

The google VPN is not compatible with Open Core Legacy Patcher -- tens of thousands of mac users who use this software to keep their macs updated will not work with the google VPN due to its usage of flutter. 

I recommend google investigates this and improves the codebase for compatibility, as flutter is not the best usage for VPNs on mac, all competitors (NORD, IVPN, Proton, Cyberghost etc) their VPN services all function correctly, therefore this makes googles VPN obsolete vs competition. 

I would position this as a huge priority as users with virtual machines will run into this issue aswell due to flutter.
Please improve MAC OSX Compatibility.  

2) 
Another work around (and additional suggestion) is to allow binding of the VPN service to routers; IE Asus routers (VPN Fusion) this in turn would be a great workaround as we can then assign this to devices. 

3)
Additionally google should open up this VPN service to allow binding for different countries; to not allow this when its been standard in the VPN industry for decades is a priority to add in.

**Comment by joetimmy** [comment]
Looking for help with all of this still.

**Comment by MeesJ** [comment]
> Looking for help with all of this still.

Why did you close your issue as completed in that case?
