### ISSUE TITLE
BSOD on Windows 10

### ISSUE THREAD

**Issue by Vap0r1ze** [google/vpn-libraries#21]
Using the latest Windows build from [Google One](https://one.google.com/about/vpn) whenever I turn on the VPN I get a BSOD.

It may be related to the fact that I'm using USB Tethering from my Pixel 3a as my internet (which is uses the Hyper-V vEthernet adapter).

The stop code I get is `INVALID_MDL_RANGE`, I would send a minidump but I think they're corrupted because they fail to open in Visual Studio.

System info:
```
Processor	AMD Ryzen 5 2400G with Radeon Vega Graphics       3.60 GHz
Installed RAM	32.0 GB
Edition	Windows 10 Pro
Version	21H2
Installed on	‎7/‎7/‎2020
OS build	19044.2788
Experience	Windows Feature Experience Pack 120.2212.3920.0
```

**Comment by mhofman** [comment]
Same issue here. Tethering over USB using a Pixel 5

**Comment by lowedaniel** [comment]
Thank you for your feedback on the libraries for VPN by Google One. Due to the planned turndown of the VPN, this repo will soon be archived. I’m marking this issue as closed. Thank you again for your input.
