### ISSUE TITLE
Please create a Google TV / Android TV client 

### ISSUE THREAD

**Issue by Mr-McMuffin** [google/vpn-libraries#33]
The current google one apk doesnt install on google tv chromecast 4k or HD, please make a VPN client for these devices.

**Comment by MeesJ** [comment]
Seconding this

**Comment by lowedaniel** [comment]
Thank you for your feedback on the libraries for VPN by Google One. Due to the planned turndown of the VPN, this repo will soon be archived. I’m marking this issue as closed. Thank you again for your input.
