### ISSUE TITLE
PLEASE open-source Bridge Datapath part

### ISSUE THREAD

**Issue by ShellWen** [google/vpn-libraries#35]
Nowadays, Google One VPN use `bridge` as datapath protocol. But this repo only contains `ipsec` datapath. No one knows the structure of the data packets except Google employees, which poses a threat to the transparency of this repository.

To ensure that all security experts can audit this code and protect user safety, please open-source this code.

**Comment by ShellWen** [comment]
@ronaldkozoman I don't know if you are still working at Google or maintaining this project, but please check it regardless.

**Comment by lowedaniel** [comment]
Thank you for your feedback on the libraries for VPN by Google One. Due to the planned turndown of the VPN, this repo will soon be archived. I’m marking this issue as closed. Thank you again for your input.
