### ISSUE TITLE
[IOS] Every time you turn on the VPN switch, the VPN configuration will be added.

### ISSUE THREAD

**Issue by illusionJP** [google/vpn-libraries#37]
Every time you turn on the VPN switch, the VPN configuration will be added. The software didn't have this problem before, but it appeared after upgrading to the latest version, and other people also had this problem.

https://github.com/google/vpn-libraries/assets/120254464/1a732957-d45b-4f66-b22c-bece5d0c479b

**Comment by lowedaniel** [comment]
Thank you for your feedback on the libraries for VPN by Google One. Due to the planned turndown of the VPN, this repo will soon be archived. I’m marking this issue as closed. Thank you again for your input.
