### ISSUE TITLE
[iOS] VPN Connection Stability - VPN Drops & Reconnects Multiple Times per Hour

### ISSUE THREAD

**Issue by iambmelt** [google/vpn-libraries#38]
The Google One VPN on my iOS device drops its connection & rejoins multiple times per hour, seemingly without cause. It does not matter whether I am on WiFi or cellular, it seems to happen at indeterminate intervals. It is not related to access point (AP) or cellular tower hopping, as there is only one AP on my home network. Sometimes the connection drops and does not rejoin. When this happens I have to navigate into Settings and then disable and reenable the VPN. VPN on Demand is enabled in Settings. 

My macOS device does not experience this issue, only my iPhone.

Device: iPhone 13 mini
iOS version: 17.2.1
Model: MNF93LL/A
App version: 1.66

**Comment by bigkahuna1uk** [comment]
This also happens on iPhone 13 Pro Max under iOS 17.3, both on cellular and wifi.  VPN is constantly reconnecting and while doing so, the kill switch is activated so the internet is blocked until the connection is reestablished.  This makes the phone unusable.  Only workaround is to toggle airplane mode on and off but that quickly becomes laborious.  I've switched the VPN off now as a result.  It's not fit for purpose.   

Works fine on iPad or mac OS Sonoma.

**Comment by iambmelt** [comment]
Version `1.69` of the app seems much more stable. /cc @bigkahuna1uk as FYI

**Comment by lowedaniel** [comment]
Thank you for your feedback on the libraries for VPN by Google One. Due to the planned turndown of the VPN, this repo will soon be archived. I’m marking this issue as closed. Thank you again for your input.
