### ISSUE TITLE
[iOS] AirDrop to macOS doesn't work when VPN is enabled

### ISSUE THREAD

**Issue by iambmelt** [google/vpn-libraries#39]
With VPN enabled, iOS device cannot AirDrop to Mac. The Mac is able to discover the iOS device, but the iOS device cannot discover the Mac. Disabling the VPN makes the Mac device discoverable.

Device: iPhone 13 mini
iOS version: 17.2.1
Model: MNF93LL/A
App version: 1.66

**Comment by lowedaniel** [comment]
Thank you for your feedback on the libraries for VPN by Google One. Due to the planned turndown of the VPN, this repo will soon be archived. I’m marking this issue as closed. Thank you again for your input.
